import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  Calculator, 
  DollarSign, 
  TrendingUp, 
  PieChart,
  Download,
  Share2,
  Info
} from 'lucide-react';
import { formatCurrency, formatCurrencyDetailed } from '../utils/currency';

const SalaryCalculator = () => {
  const [ctc, setCtc] = useState('');
  const [taxRegime, setTaxRegime] = useState('new');
  const [breakdown, setBreakdown] = useState(null);

  const calculateBreakdown = () => {
    const totalCTC = parseFloat(ctc);
    if (!totalCTC || totalCTC <= 0) return;

    // Standard CTC breakdown percentages
    const basic = totalCTC * 0.40; // 40% of CTC
    const hra = totalCTC * 0.20; // 20% of CTC
    const specialAllowance = totalCTC * 0.15; // 15% of CTC
    const employerPF = totalCTC * 0.12; // 12% employer contribution
    const employeePF = totalCTC * 0.12; // 12% employee contribution
    const bonus = totalCTC * 0.08; // 8% performance bonus
    const otherAllowances = totalCTC * 0.05; // 5% other

    // Calculate gross salary (before PF deduction)
    const grossSalary = basic + hra + specialAllowance + bonus + otherAllowances;

    // Calculate professional tax (approximate)
    const professionalTax = 2400; // Annual PT

    // Calculate taxable income
    const standardDeduction = 50000;
    const taxableIncome = grossSalary - employeePF - standardDeduction;

    // Calculate income tax based on regime
    let incomeTax = 0;
    if (taxRegime === 'old') {
      // Old regime with standard deduction
      if (taxableIncome > 1000000) {
        incomeTax = 112500 + (taxableIncome - 1000000) * 0.30;
      } else if (taxableIncome > 500000) {
        incomeTax = 12500 + (taxableIncome - 500000) * 0.20;
      } else if (taxableIncome > 250000) {
        incomeTax = (taxableIncome - 250000) * 0.05;
      }
    } else {
      // New regime (2023-24)
      if (taxableIncome > 1500000) {
        incomeTax = 187500 + (taxableIncome - 1500000) * 0.30;
      } else if (taxableIncome > 1200000) {
        incomeTax = 150000 + (taxableIncome - 1200000) * 0.20;
      } else if (taxableIncome > 900000) {
        incomeTax = 90000 + (taxableIncome - 900000) * 0.15;
      } else if (taxableIncome > 600000) {
        incomeTax = 30000 + (taxableIncome - 600000) * 0.10;
      } else if (taxableIncome > 300000) {
        incomeTax = (taxableIncome - 300000) * 0.05;
      }
    }

    // Add cess
    incomeTax = incomeTax * 1.04; // 4% cess

    // Calculate in-hand salary
    const annualDeductions = employeePF + professionalTax + incomeTax;
    const annualInHand = grossSalary - annualDeductions;
    const monthlyInHand = annualInHand / 12;

    setBreakdown({
      ctc: totalCTC,
      components: {
        basic,
        hra,
        specialAllowance,
        bonus,
        otherAllowances,
        employerPF,
      },
      grossSalary,
      deductions: {
        employeePF,
        professionalTax,
        incomeTax,
        total: annualDeductions
      },
      inHand: {
        annual: annualInHand,
        monthly: monthlyInHand
      },
      taxableIncome,
      standardDeduction
    });
  };

  const downloadReport = () => {
    if (!breakdown) return;
    
    const report = `
SALARY BREAKDOWN REPORT
========================

CTC: ${formatCurrencyDetailed(breakdown.ctc, 'INR')}

COMPONENTS:
-----------
Basic Salary: ${formatCurrencyDetailed(breakdown.components.basic, 'INR')}
HRA: ${formatCurrencyDetailed(breakdown.components.hra, 'INR')}
Special Allowance: ${formatCurrencyDetailed(breakdown.components.specialAllowance, 'INR')}
Performance Bonus: ${formatCurrencyDetailed(breakdown.components.bonus, 'INR')}
Other Allowances: ${formatCurrencyDetailed(breakdown.components.otherAllowances, 'INR')}
Employer PF: ${formatCurrencyDetailed(breakdown.components.employerPF, 'INR')}

Gross Salary: ${formatCurrencyDetailed(breakdown.grossSalary, 'INR')}

DEDUCTIONS:
-----------
Employee PF: ${formatCurrencyDetailed(breakdown.deductions.employeePF, 'INR')}
Professional Tax: ${formatCurrencyDetailed(breakdown.deductions.professionalTax, 'INR')}
Income Tax (${taxRegime === 'new' ? 'New' : 'Old'} Regime): ${formatCurrencyDetailed(breakdown.deductions.incomeTax, 'INR')}

Total Deductions: ${formatCurrencyDetailed(breakdown.deductions.total, 'INR')}

IN-HAND SALARY:
---------------
Annual: ${formatCurrencyDetailed(breakdown.inHand.annual, 'INR')}
Monthly: ${formatCurrencyDetailed(breakdown.inHand.monthly, 'INR')}

Generated by SalaryPredictor
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'salary-breakdown.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="min-h-screen pt-20"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center space-x-2 bg-primary-500/10 border border-primary-500/20 rounded-full px-4 py-2 mb-6">
            <Calculator className="h-4 w-4 text-primary-400" />
            <span className="text-sm text-primary-300">CTC Breakdown Tool</span>
          </div>

          <h1 className="text-4xl md:text-6xl font-heading font-bold text-white mb-6">
            Salary <span className="gradient-text">Calculator</span>
          </h1>
          
          <p className="text-xl text-gray-400 max-w-3xl mx-auto leading-relaxed">
            Calculate your in-hand salary, understand CTC breakdown, and compare tax regimes
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Input Section */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="glass-card p-8"
          >
            <h2 className="text-2xl font-heading font-bold text-white mb-6 flex items-center">
              <DollarSign className="h-6 w-6 text-primary-400 mr-2" />
              Enter Details
            </h2>

            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-white mb-2">
                  Annual CTC (INR) *
                </label>
                <input
                  type="number"
                  value={ctc}
                  onChange={(e) => setCtc(e.target.value)}
                  placeholder="e.g., 1200000"
                  className="input-field w-full text-lg"
                />
                <p className="text-xs text-gray-400 mt-1">Enter your total Cost to Company</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-white mb-3">
                  Tax Regime
                </label>
                <div className="grid grid-cols-2 gap-4">
                  <button
                    onClick={() => setTaxRegime('new')}
                    className={`p-4 rounded-xl border-2 transition-all ${
                      taxRegime === 'new'
                        ? 'border-primary-500 bg-primary-500/20'
                        : 'border-white/10 hover:border-white/30'
                    }`}
                  >
                    <div className="text-center">
                      <div className="text-lg font-bold text-white mb-1">New Regime</div>
                      <div className="text-xs text-gray-400">Lower rates, no deductions</div>
                    </div>
                  </button>

                  <button
                    onClick={() => setTaxRegime('old')}
                    className={`p-4 rounded-xl border-2 transition-all ${
                      taxRegime === 'old'
                        ? 'border-primary-500 bg-primary-500/20'
                        : 'border-white/10 hover:border-white/30'
                    }`}
                  >
                    <div className="text-center">
                      <div className="text-lg font-bold text-white mb-1">Old Regime</div>
                      <div className="text-xs text-gray-400">With deductions</div>
                    </div>
                  </button>
                </div>
              </div>

              <button
                onClick={calculateBreakdown}
                disabled={!ctc}
                className="btn-primary w-full text-lg py-4 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Calculator className="h-5 w-5 mr-2" />
                Calculate Breakdown
              </button>

              <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
                <div className="flex items-start space-x-2">
                  <Info className="h-5 w-5 text-blue-400 flex-shrink-0 mt-0.5" />
                  <div className="text-sm text-blue-300">
                    <p className="font-semibold mb-1">Note:</p>
                    <p className="text-xs text-blue-200">
                      This is an approximate calculation. Actual in-hand salary may vary based on company policy, 
                      additional deductions, and tax-saving investments.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Results Section */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
            className="space-y-6"
          >
            {breakdown ? (
              <>
                {/* In-Hand Salary Card */}
                <div className="glass-card p-8 text-center bg-gradient-to-br from-primary-500/10 to-blue-500/10">
                  <div className="text-sm text-gray-400 mb-2">Monthly In-Hand Salary</div>
                  <div className="text-5xl font-heading font-bold gradient-text mb-4">
                    {formatCurrency(breakdown.inHand.monthly, 'INR')}
                  </div>
                  <div className="text-sm text-gray-400">
                    Annual: {formatCurrency(breakdown.inHand.annual, 'INR')}
                  </div>
                  
                  <div className="flex items-center justify-center space-x-4 mt-6">
                    <button
                      onClick={downloadReport}
                      className="btn-secondary text-sm"
                    >
                      <Download className="h-4 w-4 mr-2" />
                      Download
                    </button>
                    <button className="btn-secondary text-sm">
                      <Share2 className="h-4 w-4 mr-2" />
                      Share
                    </button>
                  </div>
                </div>

                {/* CTC Components */}
                <div className="glass-card p-6">
                  <h3 className="text-lg font-heading font-semibold text-white mb-4 flex items-center">
                    <PieChart className="h-5 w-5 text-primary-400 mr-2" />
                    CTC Breakdown
                  </h3>
                  <div className="space-y-3">
                    {[
                      { label: 'Basic Salary', value: breakdown.components.basic, color: 'text-blue-400' },
                      { label: 'HRA', value: breakdown.components.hra, color: 'text-green-400' },
                      { label: 'Special Allowance', value: breakdown.components.specialAllowance, color: 'text-purple-400' },
                      { label: 'Performance Bonus', value: breakdown.components.bonus, color: 'text-yellow-400' },
                      { label: 'Other Allowances', value: breakdown.components.otherAllowances, color: 'text-pink-400' },
                      { label: 'Employer PF', value: breakdown.components.employerPF, color: 'text-orange-400' },
                    ].map((item, index) => (
                      <div key={index} className="flex items-center justify-between py-2 border-b border-white/10 last:border-0">
                        <span className="text-sm text-gray-300">{item.label}</span>
                        <span className={`text-sm font-semibold ${item.color}`}>
                          {formatCurrency(item.value, 'INR')}
                        </span>
                      </div>
                    ))}
                    <div className="flex items-center justify-between py-2 pt-4 border-t-2 border-primary-500/30">
                      <span className="text-sm font-bold text-white">Gross Salary</span>
                      <span className="text-sm font-bold text-primary-400">
                        {formatCurrency(breakdown.grossSalary, 'INR')}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Deductions */}
                <div className="glass-card p-6">
                  <h3 className="text-lg font-heading font-semibold text-white mb-4 flex items-center">
                    <TrendingUp className="h-5 w-5 text-red-400 mr-2" />
                    Deductions
                  </h3>
                  <div className="space-y-3">
                    {[
                      { label: 'Employee PF (12%)', value: breakdown.deductions.employeePF },
                      { label: 'Professional Tax', value: breakdown.deductions.professionalTax },
                      { label: `Income Tax (${taxRegime === 'new' ? 'New' : 'Old'} Regime)`, value: breakdown.deductions.incomeTax },
                    ].map((item, index) => (
                      <div key={index} className="flex items-center justify-between py-2 border-b border-white/10 last:border-0">
                        <span className="text-sm text-gray-300">{item.label}</span>
                        <span className="text-sm font-semibold text-red-400">
                          -{formatCurrency(item.value, 'INR')}
                        </span>
                      </div>
                    ))}
                    <div className="flex items-center justify-between py-2 pt-4 border-t-2 border-red-500/30">
                      <span className="text-sm font-bold text-white">Total Deductions</span>
                      <span className="text-sm font-bold text-red-400">
                        -{formatCurrency(breakdown.deductions.total, 'INR')}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Comparison */}
                <div className="glass-card p-6 bg-gradient-to-br from-success-500/10 to-emerald-500/10">
                  <div className="text-center">
                    <div className="text-sm text-gray-400 mb-2">Take-Home Percentage</div>
                    <div className="text-4xl font-heading font-bold text-success-400 mb-2">
                      {((breakdown.inHand.annual / breakdown.ctc) * 100).toFixed(1)}%
                    </div>
                    <div className="text-xs text-gray-400">
                      of your CTC
                    </div>
                  </div>
                </div>
              </>
            ) : (
              <div className="glass-card p-12 text-center">
                <Calculator className="h-16 w-16 text-gray-600 mx-auto mb-4" />
                <p className="text-gray-400">
                  Enter your CTC and click calculate to see the breakdown
                </p>
              </div>
            )}
          </motion.div>
        </div>
      </div>
    </motion.div>
  );
};

export default SalaryCalculator;